### ISSUE TITLE
An error displays when create new storage account

### ISSUE THREAD

**Issue by v-fional** [Microsoft/vscode-iot-workbench#112]
When try to create new storage account, and enter the storage name, then press Enter, there is an error displays in the Output.

![image](https://user-images.githubusercontent.com/15977880/36956152-b6678176-2067-11e8-98ef-3f0dc1a4db3a.png)

**Comment by Sneezry** [comment]
It works fine on my side with the latest version of functions extension and workbench extension. We need further verification.

**Comment by Sneezry** [comment]
This issue should be caused by missing prerequisites. By following guide [here](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions#user-content-prerequisites), this issue should be fixed.

**Comment by v-fional** [comment]
After install the prerequisites, the error cannot repro, so close it
