### ISSUE TITLE
"Esc" key doesn't work correctly

### ISSUE THREAD

**Issue by v-fional** [Microsoft/vscode-iot-workbench#126]
**Steps:**
1. Launch VSCode
2. Press F1, select "IoT Workbench project: Azure Provision" -> ">> 1. IoT Hub - 2. IoT Hub Device - 3. Azure Function" -> "Create a new IoT Hub" -> select subscription -> create resource group
3. When the "Resource Group Name" textbox displays, press Esc key to cancel this operation

**Expected:**
1. The "azure provision" should be cancelled, without any exception

**Actual:**
There is an error - "Cannot read property 'length' of null", please refer to the following screenshot

The Esc doesn't work correctly, the function seems to equal to press Enter key

![image](https://user-images.githubusercontent.com/15977880/37078128-db05d33a-2192-11e8-9841-6a0d59a82c6e.png)

**Comment by ArthurMa1978** [comment]
Consider to report warning instead of error

**Comment by v-fional** [comment]
If click ESC, the warning message "provision canceled" displays or directly close the dropdown list, so close the issue
