### ISSUE TITLE
If workspace is not empty and try to create a new project, the message should be keep consistent

### ISSUE THREAD

**Issue by v-fional** [Microsoft/vscode-iot-workbench#152]
**Steps:**
1. Launch ShakeShake example
2. Run "IoT Workbench: New", verify the message
3. Launch GetStarted example
4. Run "IoT Workbench: New", verify the message

**Expected:**
1. The message should be equal

**Actual:**
1. For step 2, the message is "There are multiple workspaces in the project. Initialize new project in workbench directory?"

![image](https://user-images.githubusercontent.com/15977880/37331481-09068800-26df-11e8-9ba8-7af4f0add1dc.png)

2. For step 4, the message is "An empty folder is required to initialize the project. Initialize new project in workbench directory?"

![image](https://user-images.githubusercontent.com/15977880/37331527-22d5c9ee-26df-11e8-9bdb-3129e900694b.png)

**Comment by Sneezry** [comment]
The code logic is correct, but we may need to discuss about user experience.

> There are multiple workspaces in the project. Initialize new project in workbench directory?

This message shows when there are multi folders in current workspace. ShakeShake example contains Device and Function folder, and the extension do not know which folder it should initialize the project in.

> An empty folder is required to initialize the project. Initialize new project in workbench directory?

This message shows when there is one folder in current workspace, but the folder is not empty. GetStarted  example only contains Device folder, and the extension knows that it should initialize the project in Device folder. But it finds Device folder is not empty immediately, so it should not create new project within that folder.

**Comment by Sneezry** [comment]
As discussion with Arthur, we close this issue.
