### ISSUE TITLE
The output folder is not specified 

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-iot-workbench#159]
Add below line to the template
"output": "./.build"

**Comment by czgtest** [comment]
Test steps:
1.	open vscode and install workbench extension
2.	Press F1 and select IoT workbench:example and try Get Started example
3.	Open Get Started project 
Verify output folder is specified in Arduino.json
 
![image](https://user-images.githubusercontent.com/35018765/38788573-207c010c-4167-11e8-9b86-b684c55fa31c.png)

4.	Press F5 and select Arduino: verify
After verify pass , you can see the .build folder in project subfolder
 
![image](https://user-images.githubusercontent.com/35018765/38788568-1c85017a-4167-11e8-9b2d-1ceee28e0994.png)

5.	Open project.code-workspace via vscode 
Verify the .build folder is not opening in project 
![image](https://user-images.githubusercontent.com/35018765/38788562-129a7208-4167-11e8-90aa-375fb894e947.png)
