### ISSUE TITLE
Creating a new project from template takes longer than usual

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-iot-workbench#178]
It is probably due to the lazy loading of the extension. We can think about adding progress information in the output window.

https://mseng.visualstudio.com/VSIoT/_workitems/edit/1224032

**Comment by Sneezry** [comment]
This depends on VSCode. We may change activation rule of the extension to solve this issue.

I opened a new issue to track this task: https://github.com/Microsoft/vscode-iot-workbench/issues/194
