### ISSUE TITLE
Auto downloading the package of AZ3166

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-iot-workbench#180]
Currently, user need to operate in the UI of Arduino extension manually.

**Comment by ArthurMa1978** [comment]
Need export new API from Arduino extension

**Comment by czgtest** [comment]
Test sceanrio1 : 
Test result:
Pre-steps:
1.remove package :MXChip - Microsoft Azure IoT Developer Kit
2.delete arduino.additionalUrls in vscode user settings
3.delete additional boards manager URLs from Arduino IDE

steps:
1.open vscode 
2.press F1 and input iot workbench:New->select Iot DevKit board -> create an device project
verify it will auto install package -AZ3166
![image](https://user-images.githubusercontent.com/35018765/38729069-510e5826-3f44-11e8-8c80-cf8d8d36cb70.png)

**Comment by czgtest** [comment]
Use the latest Arduino package vscode-arduino-0.2.13-rc2.vsix and workbench package vscode-iot-workbench-0.1.1-rc2.vsix , it fix work now,
![image](https://user-images.githubusercontent.com/35018765/38855642-9aa6e880-4256-11e8-899d-0f25f5bd633b.png)
