### ISSUE TITLE
Don't activate on * unless you have to

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-iot-workbench#280]
I don't know if it is a requirement, but it is generally not a good practice to activate on "*" (see https://code.visualstudio.com/docs/extensionAPI/activation-events#_activationevents).   This helps keep the startup speed of VS Code as quick as possible.

**Comment by Sneezry** [comment]
Thanks for your suggestion.

The extension needs to listen USB, and automatically download necessary package and show example gallery when supported board connects to computer.

**Comment by chrisdias** [comment]
make sense, thanks!
