### ISSUE TITLE
[Raspberry Pi][Doc] Improve the doc of raspi-get-started and raspi-simple-led

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#325]
![image](https://user-images.githubusercontent.com/35018765/42310046-fa95f16a-806c-11e8-92ec-67e9845789f9.png)

raspi-simple-led.md 
![image](https://user-images.githubusercontent.com/35018765/42310083-1503dd50-806d-11e8-8d3f-e2ca02466adc.png)

**Comment by lirenhe** [comment]
The doc is updated
