### ISSUE TITLE
[RaspberryPi]unable to create folder for examples and unable to load example

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-iot-workbench#377]
OS:  windows10 
latest vscode

pre-step:
install workbench 0.1.9-rc

step:
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/raspberry-pi/raspi-get-started.md
Open IoT Workbench Examples
1.select IoT Workbench: Examples.
2.Select Raspberry.  then the IoT Workbench Example window is showed up.
3.Find Get Started and click Open Sample button. 
4. click Open Sample button again
you can see this error.

![image](https://user-images.githubusercontent.com/35018765/43878661-f6452064-9bd2-11e8-8bc5-ee99de762445.png)

**Comment by robinsh** [comment]
I have the same problem with just opening the first samples for the MXChip IoT Devkit. Can't open it, same reasons as posted here for raspberry pi. Tried running VS Code in admin mode in case it helped, but it didn't. Could really use some help on this, as I am giving a talk on this next week, and need to load the samples so I can finish writing the talk.
