### ISSUE TITLE
An error occurred while uploading the sketch

### ISSUE THREAD

**Issue by MSKeith** [Microsoft/vscode-iot-workbench#403]
All,
    I am getting the following error:

Error: libusb_open() failed with LIBUSB_ERROR_NOT_FOUND
Error: open failed
in procedure 'program' 
in procedure 'init' called at file "embedded:startup.tcl", line 495
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked

An error occurred while uploading the sketch
[Error] Exit with code=1

when I try to upload the code to the 3166.  the program will compile correctly...and I am not sure why I am getting this error...thoughts?

K

**Comment by lirenhe** [comment]
Did you install the stlink driver for AZ3166? https://www.st.com/en/development-tools/stsw-link009.html

**Comment by MSKeith** [comment]
Well, I am not sure if that driver was installed or not, but I can tell you that it does pick up a com port, and I can connect to the serial interface of the device...so it seems that the board driver is recognized.

**Comment by MSKeith** [comment]
You...Renhe Li... are a genius.  I just installed the driver and code pushed to the device with out an issue.

thank you...
K

**Comment by lirenhe** [comment]
you are welcome. Then I will close this issue. Please let us know if you face other problems.
