### ISSUE TITLE
ESP32 is not listed in Select Board option

### ISSUE THREAD

**Issue by sukeshak** [microsoft/vscode-iot-workbench#408]
Use F1 or Ctrl+Shift+P (macOS: Cmd+Shift+P) to open the command palette, type IoT Workbench, and then select IoT Workbench: Examples.

Have configured and gone through the previous steps already

ESP32 is not listed in Select Board option
![no-esp32-listed](https://user-images.githubusercontent.com/9167668/44904736-a6e59f00-ad2d-11e8-9df9-1dfb4df5361b.png)

**Comment by Sneezry** [comment]
ESP32 examples are not available in current public release. But we will ship it in the next few days.

**Comment by sukeshak** [comment]
Thanks @Sneezry 
Is there a way to get notified? Is there a work item I can monitor specific to ESP32?
Interested in DPS & OTA examples as well.

**Comment by Sneezry** [comment]
As far as I know, DPS and OTA examples for ESP32 would not be available in the next release, but it's in our plan: https://github.com/Microsoft/vscode-iot-workbench/issues/390

I cannot guarantee date of the next release, but it should be the next week.

**Comment by sukeshak** [comment]
Is this finally released publicly yet? 
What was the point on announcing public availability on MS Blog and not having it available?

**Comment by Sneezry** [comment]
Hi @sukeshak , we just released v0.1.10, which has ESP32 examples available. We announced ESP32 support available on MS Blog is not for example gallery, but you can create new ESP32 project with IoT Workbench. However, you can try ESP32 examples with the latest version IoT Workbench. OTA example is also available for IoT DevKit as we said on MS Blog. For ESP32 OTA example is not in our plan yet, sorry for the mistake message I posted.

**Comment by sukeshak** [comment]
Thank you for the response @Sneezry 

I just checked and found the ESP32 enabled in the menu. 
I tried it earlier when the blog showed up but that time ESP32 was not listed in the menu (screenshot in the first post here).

Are there any plans to have the same with ESP-IDF support (FreeRTOS) as well instead of Arduino?
