### ISSUE TITLE
get error when press ESC to cancel select workbench folder

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#417]
pre-step:
install  workbench0.1.10-rc

step:
1. open welcome-Azure IoT Workbench

2.click Examples--select ESP32 Arduino Esp32

3. go to esp32 page and click"open Sample" for Get Started,  
you can see select workbench folder will display, it work well

4. then press ESC to cancel select workbench folder

you can see the error will throw.

Unable to create folder for examples, please check the workbench settings.

![image](https://user-images.githubusercontent.com/35018765/45288652-c5158100-b51d-11e8-9e59-386e9d759d8f.png)

**Comment by Sneezry** [comment]
This is as designed. `IoTWorkbench.workbench` is a required setting without default value, and if the user doesn't provide a folder path for the extension, the extension throws errors.
