### ISSUE TITLE
[doc] improve the steps of OTA tutorial

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#419]
page 
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-ota.md

Config IoT Hub Connection String
Issue: should be add one step after step4
![image](https://user-images.githubusercontent.com/35018765/45334326-deb1d980-b5ac-11e8-816c-14d758c3a899.png)

Calculate the CRC value 
replace this manually step with run command "IoT workbench: device" --->"Generate CRC"

Upload the firmware to cloud
step2: Navigate to your new storage account in the Azure portal,  scroll to the Blob Service section, then select Browse Blobs.Create a public container for storing firmware files.

**Comment by lirenhe** [comment]
Fixed in https://github.com/Microsoft/vscode-iot-workbench/pull/468
