### ISSUE TITLE
[Generate CRC]improve the message to tell user run device complie

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#420]
pre-step:
install workbench 0.1.10-rc

steps:

1. IoT workbench : example --open OTA sample

2.IoT workbench :device -- Generate CRC

there is a warning message :  No bin file found

Can we give a message to reminder user run "device complie" first ?

**Comment by lirenhe** [comment]
Fixed #469  will be released in 0.1.13
