### ISSUE TITLE
IoT Workbench project doesn't work after restarting vs code

### ISSUE THREAD

**Issue by clovett** [Microsoft/vscode-iot-workbench#428]
Invoke the "IoT Workbench: new" command, select DevKit MXCHIP, and "Device Only". Now build it with "Device Compile" and everything is good right? Now close vs code and reopen it. Try and compile? You get error saying: "Unable to upload device code, please open an IoT Workbench project and retry."

```
Extension | Author (truncated) | Version
----------- | -------------------- | --
vscode-azurefunctions | ms- | 0.10.2
python | ms- | 2018.7.1
azure-account | ms- | 0.4.3
cpptools | ms- | 0.18.1
code-spell-checker | str | 1.6.10
azure-iot-toolkit | vsc | 1.3.0
vscode-arduino | vsc | 0.2.20
vscode-iot-workbench | vsc | 0.1.10
```

**Comment by lirenhe** [comment]
I tried the same step but I am unable to repro this issue.  For 'close vs code and reopen it', did you open the workspace by using project.code-workspace file?  The IoT Workbench project could not be loaded if you open the folder directly.

**Comment by clovett** [comment]
Oh, I see, didn't realize you had to open the project.code-workspace, that wasn't clear to me.  Works now, thanks :-)
