### ISSUE TITLE
Randomly not finding my local include files

### ISSUE THREAD

**Issue by clovett** [microsoft/vscode-iot-workbench#430]
I have an IOT Workbench project with some local include files, and if I delete the build folder and comment out this line:
```
#include "EnergyNormalizer.h"
```
and reload vscode it compiles, deploys, runs, all is good, and the main *.ino file includes some local header only files.  But sometimes when I change my .ino file and compile it says:
```
KeywordSpotter:9:30: error: EnergyNormalizer.h: No such file or directory
```
I have some local header files and it seems to be getting confused and is not following the [Arduino build process](https://github.com/arduino/Arduino/wiki/Build-Process).  Instead, it is generating "EnergyNormalizer.h.cpp" which confuses things.  But according to the build process, it should be creating KeywordSpotter.ino.cpp.   What is weirder, is I have other header files in the same project and those are working fine.  They are copied to the build/sketch folder and work fine.

What I'm finding is is the "sketchLocation" property in build.options.json is getting set incorrectly... it is always pointing at one of my headers and therefore it was creating a bogus header.h.cpp file...
```
  "sketchLocation": "d:\\git\\ELL\\ELL-firmware\\MXCHIP\\KeywordSpotter\\Device\\EnergyNormalizer.h",
```
and editing this manually doesn't solve the problem, it keeps getting overwritten.  You can see the weirdness here:

![image](https://user-images.githubusercontent.com/3336415/45610443-c577b580-ba10-11e8-96a0-b89215c20d9c.png)

**Comment by owensc84** [comment]
I am having the same problem.  Everything had been working fine for weeks and all the sudden I get the issue here.  My source files are in a folder called "src", changing this folder name to the sketch name allowed the build to succeed again.

**Comment by ArthurMa1978** [comment]
It's caused by the Arduino IDE which is out of our control.
Now we are trying to use new Arduino Cli which suppose be much better but still need time for investigating and testing.
