### ISSUE TITLE
Examples with Azure Functions boots with errors

### ISSUE THREAD

**Issue by liydu** [Microsoft/vscode-iot-workbench#436]
We got several reports from Ignite that DevKit examples with Azure Functions got error when bootstrap.

The Function App  has a parameter set to 1 (WEBSITE_RUN_FROM_PACKAGE). when provisioned. this parameter is meant to allow faster cold start of a function, but has it has a caveat: it makes the function file system read only... so the Nuget Restore doesn't work... 

We need to explicitly set WEBSITE_RUN_FROM_PACKAGE to 0 to avoid the fast code start.

**Comment by Sneezry** [comment]
v0.1.11 hotfix has been shipped.
