### ISSUE TITLE
Setting the Device Connection String doesn't work through vscode on MacOS

### ISSUE THREAD

**Issue by JosephPaulAntonetti** [Microsoft/vscode-iot-workbench#437]
macOS Mojave on MacBook Pro 2016.

When I attempt to set the connection string on the device through the IoT Device menu, the connection string is not set. However, manually setting the connection string by connecting via serial and stepping through configuration does work.

**Comment by Sneezry** [comment]
This is a known issue on macOS. We use `screen` command to connect to serial port on macOS. Sometimes, `screen` doesn't connect to serial port correctly. This issue may be related with macOS. And we do not have a good solution currently, yet.

**Comment by lirenhe** [comment]
Could you open command line and type **screen /dev/cu.usbserial 115200** and check the result?  Please replace /dev/cu.usbserial with the serial port of IoT Devkit.

**Comment by JosephPaulAntonetti** [comment]
@lirenhe - The result of the command shows me a list of things I can do (configure WiFi, set connection string, etc.).

**Comment by wgcv** [comment]
Connect the board and try in the terminal:
```
ls /dev/cu.usbmodem*
screen /dev/cu.usbmodemXXXX 115200 –L
set_az_iothub [device connection string ]
```
The Device connection string is in azure azure: Home -> All resources -> XXX- IoT devices -> Device details

**Comment by lirenhe** [comment]
We will provide the workaround for MacOS serial port problem in DevKit-SDK.
https://github.com/Microsoft/devkit-sdk/issues/931
