### ISSUE TITLE
Select IoT Hub shows only 3 subscriptions

### ISSUE THREAD

**Issue by damadei** [Microsoft/vscode-iot-workbench#451]
Issue Type: <b>Bug</b>

I have like 10 subscriptions associated to my account however when I execute the Azure Iot Hub: Select IoT Hub, it pops up only 3 subscriptions, not the entire list.

Extension version: 0.1.11
VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (5.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Sneezry** [comment]
Hi @damadei , have you filtered your subscriptions? Click your Azure account in vscode (at bottom left corner), and see your subscription filter list. Check subscriptions you'd like to use.

![2018-10-09](https://user-images.githubusercontent.com/1621293/46682019-16995480-cc1f-11e8-8c91-753a2d92d968.png)

**Comment by damadei** [comment]
Hi Zhe,

That was it! I never did the filter but they were filtered. Thanks a lot.

Daniel
