### ISSUE TITLE
Filter out the iot edge device when select an iot hub device

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#456]
select an existing IoT Hub device

![image](https://user-images.githubusercontent.com/35018765/46936014-81b7b080-d08f-11e8-9eda-1c2ad2ab5fdf.png)

select an IoT Hub Device.   but why IoT edge devices is display ? 

![image](https://user-images.githubusercontent.com/35018765/46936038-98f69e00-d08f-11e8-93d8-539250e006c7.png)

**Comment by ArthurMa1978** [comment]
Low priority
