### ISSUE TITLE
Add a new example to esp32 Arduino examples

### ISSUE THREAD

**Issue by lzyms** [Microsoft/vscode-iot-workbench#460]
Name: ESP32 Azure IoT central
Folder name: esp32_iot_central
Description: Azure IoT Central example for esp32-azure-kit board
Location: https://github.com/lzyms/ESP32IoTCentral
Image : https://github.com/lzyms/ESP32IoTCentral/blob/master/images/esp32-board.jpg
Tutorial : https://github.com/lzyms/ESP32IoTCentral/blob/master/README.MD
Difficulty :  Medium

**Comment by lirenhe** [comment]
Added. Thanks @lzyms for the contribution.
