### ISSUE TITLE
Unresolved dependencies in project.json

### ISSUE THREAD

**Issue by ananth3010** [Microsoft/vscode-iot-workbench#461]
Hi

I'm a total newbie to .Net hence need help to run this example.

When I open the sample project of DevKit translator in VS Code, I get the below issues: 

1. WARNING: project.json is no longer a supported project format for .NET Core applications. Update to the latest version of .NET Core (https://aka.ms/netcoredownload) and use 'dotnet migrate' to upgrade your project (see https://aka.ms/netcoremigrate for details).

When I run dotnet migrate the "project.json" is deleted and the entire workspace is corrupted. Hence I ignore the warning.

2. There are unresolved dependencies from 'Functions\devkit-translator\project.json'. Please execute the restore command to continue.

When I restore the project, I'm hit with this error: c:\Users\anjayak\Documents\IoTWorkbenchProjects\examples\devkit_translator\Functions\devkit-translator\project.json(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
Done: 1.

A google states that a new file global.json needs to be added to the project. Can someone please help with this issue?

**Comment by lirenhe** [comment]
@ananth3010 , currently, our examples are built with Azure Functions in C# Script. So please ignore the warning and do not migrate the project. Please follow the tutorial directly and it should work.
