### ISSUE TITLE
open preproc\ctags_target_for_gcc_minus_e.cpp: The system cannot find the path specified.

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode-iot-workbench#462]
Still getting this error on almost every other build, have to keep deleting the local build folder
```
[Starting] Upload sketch - KeywordSpotter.ino
Please see the build logs in Output path: d:\git\ELL\ELL-firmware\MXCHIP\KeywordSpotter\Device\build
Loading configuration...
Initializing packages...
Invalid version found: 5_4-2016q3
Preparing boards...
Verifying...
Build options changed, rebuilding all
open preproc\ctags_target_for_gcc_minus_e.cpp: The system cannot find the path specified.
[Error] Exit with code=1
```

**Comment by lirenhe** [comment]
@lovettchris, as I know, Arduino has some limitation of subfolder support in the project. The source code should either in the same folder of .ino file or it should be put into src folder.  So what is your folder structure for you project?

**Comment by ArthurMa1978** [comment]
this is Arduino defect and we can't fix it, so close this issue
