### ISSUE TITLE
IrDa send information

### ISSUE THREAD

**Issue by wgcv** [microsoft/vscode-iot-workbench#465]
Hi
I'm checking the IRremote library for arduino but doesn't work with the az3166; also I'm checking the documentation (https://microsoft.github.io/azure-iot-developer-kit/docs/apis/irda/) but I don't know how to send a infrared command with *char .

For example turn on LG TV (http://www.remotecentral.com/cgi-bin/files/rcfiles.cgi?area=prontong&db=discrete&br=lg&dv=2008television) the code is:

0000 006d 0022 0002 0157 00ac 0015 0016 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0689 0157 0056 0015 0e94

How i put that in char?

**Comment by ArthurMa1978** [comment]
create char array which contains all your IrDA code then call the api
