### ISSUE TITLE
Arduino package install failure after reinstalling VS Code

### ISSUE THREAD

**Issue by clovett** [microsoft/vscode-iot-workbench#467]
I get a bunch of errors when I open VS code after reinstalling it.  I deleted the C:\Users\Chris\AppData\Local\Arduino15 before reinstalling, but now when VS code first launches I see all these errors:

[log.txt](https://github.com/Microsoft/vscode-iot-workbench/files/2536119/log.txt)

**Comment by lirenhe** [comment]
This seems to be an Arduino problem. Could you access http://downloads.arduino.cc/packages/package_index.json

**Comment by clovett** [comment]
yep, can access that just fine.

**Comment by lirenhe** [comment]
You could try to delete package_index related files under C:\Users\{your alias}\AppData\Local\Arduino15\ and have another try.

**Comment by clovett** [comment]
yes, I already tried that. As I stated in my post above, I deleted all of C:\Users{your alias}\AppData\Local\Arduino15\ , restarted vs code, same problem.  I'm not sure the setup actually failed though.  I do see files under C:\Users\Chris\AppData\Local\Arduino15\packages\AZ3166\... and the first GettingStarted sample seems to build... perhaps the error messages can be ignored, but they are very confusing.

**Comment by lirenhe** [comment]
Could you uninstall IoT-workbench & Arduino extension from Vscode and re-install them again. Before that, clean up the folder of C:\Users\Chris\AppData\Local\Arduino15

**Comment by clovett** [comment]
I think I found the problem I also had to delete the following to get a fresh reinstall:
```
%USERPROFILE%\.vscode
%USERPROFILE%\AppData\Roaming\Code
%USERPROFILE%\AppData\Roaming\Visual Studio Code
```
but after reinstall, when I install IOT workbench still I see these errors:
```
Cannot find Arduino IDE. Please specify the "arduino.path" in the User Settings. Requires a restart after change
```
java.io.IOException: Can't extract file C:\Users\Chris\AppData\Local\Arduino15\packages\AZ3166\tools\openocd\0.10.0\bin\libgcc_s_sjlj-1.dll, file already exists!
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:212)
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:81)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:142)
	at processing.app.Base.<init>(Base.java:324)
	at processing.app.Base.main(Base.java:145)
[Error] Exit with code=255
```
have you actually followed these steps to see if you can reproduce the problem?

**Comment by lirenhe** [comment]
We got some report previously about such error. but I am unable to repro that.  For clean installation, please also remove related extensions from 'C:\Users\{alias}\.vscode\extensions'.
