### ISSUE TITLE
[Get Started][Pi Doc]  Enable I2C on Raspberry Pi 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-iot-workbench#482]
update doc in page
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/raspberry-pi/raspi-get-started.md

What you need
A Raspberry Pi.
Enable SSH/I2C on Raspberry Pi and install Node.js.

**Comment by ArthurMa1978** [comment]
Will retire these kind of node.js sample soon, so want fix
