### ISSUE TITLE
[doc] rename from Azure IoT Workbench to Azure IoT Device Workbench in docs

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#526]
after publishing workbench 0.2.0, should be change name for Azure IoT Device Workbench in docs

https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-button/teXXmo_IoT_button_get_started.md

https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-state.md

https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit_door_monitor.md

**Comment by Sneezry** [comment]
All docs have been ready under `condidate` branch. See

https://github.com/Microsoft/vscode-iot-workbench/blob/condidate/docs/iot-button/teXXmo_IoT_button_get_started.md

https://github.com/Microsoft/vscode-iot-workbench/blob/condidate/docs/iot-devkit/devkit-state.md

https://github.com/Microsoft/vscode-iot-workbench/blob/condidate/docs/iot-devkit/devkit_door_monitor.md
