### ISSUE TITLE
[Devkit] Create Azure Functions of Devkit will be blocked by a waring prompt box

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#529]
steps:

1. Azure IoT Device Workbench: Create Project
2.select IoT Devkit
3.select with Azure Functions
4.creating new project

Here I think the project will be created automatically.I waited for a long time and the project was never created.Even though I saw a waring prompt box, I didn't expect it to affect the creation of files.

user must click "skip for now" button to create project.  This setting makes me confused.

![image](https://user-images.githubusercontent.com/35018765/49921478-92966e00-fee8-11e8-8963-396e98b5fb25.png)

**Comment by Sneezry** [comment]
This notification is from Azure Functions extension, and is not under our control.
