### ISSUE TITLE
[IoT button] create new project with Azure IoT Hub

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#530]
steps
1.Azure IoT Device Workbench: Create Project
2.select IoT button
3.select with Azure IoT Hub
verify the userdata.json of project only has one link code.   is it right?

why do we add the "with Azure IoT Hub"?  Can we delete this item from create option?
![image](https://user-images.githubusercontent.com/35018765/49922096-8f03e680-feea-11e8-859a-909afa9f19eb.png)

**Comment by Sneezry** [comment]
> verify the userdata.json of project only has one link code. is it right?

It is as expect. `userdata.json` contains payload content of user data, and it can be changed to any JSON data.

> why do we add the "with Azure IoT Hub"? Can we delete this item from create option?

No. We shouldn't remove that. IoT button **must** connect to IoT Hub, and no "device only" option for this device.
