### ISSUE TITLE
[Rasperry Pi] the app.js is empty

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#531]
1.Azure IoT Device Workbench: Create Project
2.select Raspberry pi
3.select  device only
4.creating new project

verify the app.js is empty , is it right ?
![image](https://user-images.githubusercontent.com/35018765/49922592-24ec4100-feec-11e8-8c2e-d0801b2d6264.png)

**Comment by Sneezry** [comment]
This is as expect. There's nothing we can provide for a device only project for Raspberry Pi. However, you should see some code snippet if you create a project with IoT Hub.
