### ISSUE TITLE
[help page] the help page will jump to teXXmo-IoT-Button page

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#532]
1.Azure IoT Device Workbench: Help
2.verify the page is teXXmo-IoT-Button page

Users want to get more workbench information from the help page, why is it just a simple jump toteXXmo-IoT-Button page?

https://catalog.azureiotsolutions.com/details?title=teXXmo-IoT-Button&source=home-page&kit=teXXmo-IoT-Button-Starter-Kit

**Comment by Sneezry** [comment]
If the current opened workspace is an IoT workbench project for specific device, help command will open the specific device help page. This is as designed.
