### ISSUE TITLE
[survey] user can't do survey for the second times

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#533]
Azure IoT Device Workbench: Open Examples 
click My device is not in the list-
open survey page and do a survey  : want to add Esp8266 examples

Azure IoT Device Workbench: Create Project
click My device is not in the list
here user want to create Arduino examples
click yes to do a survey again
![image](https://user-images.githubusercontent.com/35018765/49923631-17848600-feef-11e8-8eb3-d37c43fdaf37.png)

user can't do a survey again.

![image](https://user-images.githubusercontent.com/35018765/49923650-29febf80-feef-11e8-9dc1-c8e03326dccf.png)

**Comment by Sneezry** [comment]
The survey can be taken only once for every unique user. This is designed on survey monkey side.
