### ISSUE TITLE
[DPS] DPS example failed after device upload

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#534]
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit_dps.md
follow the steps of devkit-dps
it will display "DPS failed" on devkit screenshot after device upload

**Comment by czgtest** [comment]
![image](https://user-images.githubusercontent.com/35018765/49979768-7d265000-ff8b-11e8-81d3-6be7d2b41ea3.png)

**Comment by czgtest** [comment]
This morning I do DPS example again ,  it can send message successfully, please see it in screenshot ,  so close 534.

**Comment by DanKline** [comment]
I'm experiencing this issue.  Apparently auth is failing during the retrieval of the key.
Info:    DPS Version: 1.2.12

Info: >>>Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED

Registration status: CONNECTED
PUT #####removed for security######/register?api-version=2018-09-01-preview HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
content-length: 44


len: 44
{ "registrationId":"az-#############" }


HTTP Status: 401

date: Fri, 15 Mar 2019 19:43:02 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
x-ms-request-id: f40da7ba-8c91-4796-8fc3-89e1dfbdbe05
strict-transport-security: max-age=31536000; includeSubDomains

{"errorCode":401002,"trackingId":"f40da7ba-8c91-4796-8fc3-89e1dfbdbe05","message":"Invalid certificate","timestampUtc":"2019-03-15T19:43:02.7904455Z"}

Error: Time:Fri Mar 15 19:43:02 2019 File:C:\Users\v-zuhu\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.6.0\cores\arduino\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:prov_transport_process_json_reply Line:323 failure retrieving json auth key value
Error: Time:Fri Mar 15 19:43:02 2019 File:C:\Users\v-zuhu\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.6.0\cores\arduino\azure-iot-sdk-c\provisioning_client\src\prov_transport_http_client.c Func:prov_transport_http_dowork Line:941 Unable to process registration reply.
Error: Time:Fri Mar 15 19:43:02 2019 File:C:\Users\v-zuhu\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.6.0\cores\arduino\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:on_transport_registration_data Line:572 Failure retrieving data from the provisioning service
Error: Time:Fri Mar 15 19:43:02 2019 File:C:\Users\dan\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.6.1\libraries\AzureIoT\src\DevkitDPSClient.cpp Func:register_device_callback Line:146 Failure encountered on registration!
Error: Time:Fri Mar 15 19:43:03 2019 File:C:\Users\dan\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.6.1\libraries\AzureIoT\src\DevkitDPSClient.cpp Func:DevkitDPSClientStart Line:314 registration failed!
