### ISSUE TITLE
COM Port access denied

### ISSUE THREAD

**Issue by aldente-dev** [microsoft/vscode-iot-workbench#537]
Hello,
When I connect MxChip board to Windows 10 PC via USB and try to execute "IoT Device Workbench:Configure Device Settings...", following message is shown in terminal.
Opening COM3: Access denied
The same situation happens when I start "Serial Monitor" by VS Code right bottom button.
Please let me know how to solve this problem.

**Comment by Sneezry** [comment]
You cannot configure device settings while monitoring serial port. You need to release serial port before execute the command.

**Comment by aldente-dev** [comment]
This problem seems to happen when other VS Code windows are opening.
I think each VS code try to connect to COM port. Is it right?

**Comment by Sneezry** [comment]
It depends. By default, vscode won't try to connect to serial port. Only in these cases vscode will try to connect to serial port:

1. Execute device upload
2. Open serial monitoring
3. Config device settings (including config connection string and UDS)
