### ISSUE TITLE
MxChip Get Started sample doesn't work

### ISSUE THREAD

**Issue by aldente-dev** [Microsoft/vscode-iot-workbench#538]
I'm trying MxChip Get Started sample but telemetry messages doesn't come to IoT Hub.
By putty I checked what happens.
2018-12-18 01:50:41 ERROR: File:iothub_client_ll.c Func:IoTHubClient_LL_CreateFromConnectionString Line:836, iotHubName is not found

I've done by command palate "Configure Device Settings..." and it seems to be succeeded.
Are there any work should I do?

**Comment by Sneezry** [comment]
This error occurs if you haven't config connection string or the connection string is invalid. You can try to config device connection string again to check if error remains. BTW, you need provision Azure services first before config device connection string.

**Comment by aldente-dev** [comment]
This problem has been resolved.
My board's firmware was little bit old. I've updated it then the sample works well.
