### ISSUE TITLE
[DevKit_state] "Deploy to Azure..." fails with error MSB1003

### ISSUE THREAD

**Issue by Kornelis** [microsoft/vscode-iot-workbench#553]
Hi, 

when following the Steps of the Devkit State Example (https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-state.md), I receive the following error when trying to Deploy the Azure Function using the " Azure IoT Device Workbench: Deploy to Azure...." Command:

```
> Executing task in folder Functions: dotnet clean --configuration Release <

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

When entering the "Functions" Folder in a powershell console and running the clean command manually everything works as expected.

I'm using Version: 1.30.1 and Azure IoT Device Workbench 0.2.1

As a workaround I deployed the Function using VS2017 which also worked as expected.

Any Idea what whats wrong when trying to deploy via VS Code?

Cheers

Kornelis

**Comment by Sneezry** [comment]
Did you open the project as folder or workspace?

**Comment by Kornelis** [comment]
I opend the Project as Workspace. 

I also tried to open the project as Folder and copy the `Functions.csproj` to the root, but that didn't work either.

Is there any advance / verbose logging I can enable (sorry... I'm not very familiar with VS Code)

**Comment by lirenhe** [comment]
Are you using the latest version of dotnet core？ There are prerequisites defined in https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions

**Comment by Kornelis** [comment]
I was using dotnet core 2.1.502 and just updated to 2.2.101 but still it doesn't work:

```
> Executing task in folder Functions: dotnet clean --configuration Release <

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

As said, when calling `dotnet clean --configuration Release` directly within the `"C:\<pathToExamples>\devkit_state\Functions\"` Folder in a Powershell Window it cleaning the output. So I would guess that a wrong working Directory is used by VS Code but I have no idea how to find out which one is used.

**Comment by lirenhe** [comment]
Could you try to use .net command directly?
In VS Code,  F1 => .NET: Restore Project, and select 'Functions.csproj' in functions folder.

**Comment by Kornelis** [comment]
The Restore Command also worked as expected.

**Comment by Kornelis** [comment]
Unfortunately opening the Fuctions Folder directly in VS Code and trying to run "Azure Functions: Deploy to Function App..". Only after deleting the .vscode folder inside the Functions Folder and "reconfigure" the whole Fucttions Setup (runtime, language,...) after running  "Azure Functions: Deploy to Function App.." the deploy finished successfuly

**Comment by lirenhe** [comment]
That is interesting. After reconfigure, there should be another .vscode folder generated, could you let us know the major difference between them?

**Comment by JerryYangKai** [comment]
Hi @Kornelis ,  can you repro your issue on the latest version of workbench?
