### ISSUE TITLE
Mac Instructions for connecting Arduino with VS Code are incorrect

### ISSUE THREAD

**Issue by klday** [Microsoft/vscode-iot-workbench#568]
On Mac, in VS Code, there is no Open File > Preference > Settings path.  I can find a settings.json file and add the lines as instructed (although I believe there is a typo for arduino.path which should be /Applications).  But, when I open the command pallette and type arduino, nothing is found.

**Comment by danuw** [comment]
Hi done that yesterday and it worked fine. You have to check you followed the instructions and actually installed the the Arduino.app inside the applications folder.

If you use Ctrl+Shift+G (I think) to open the address bar in Finder, you should be able to try and go to "/Applications".

If you cannot find the application there, then you may want to install/copy it to that location (or provide the correct location maybe?).

I remember thinking did it actually work and may have restarted VS Code and then it worked fine.

Hope that helps

**Comment by ayamane** [comment]
I had the same issue and had to install Arduino from the Extensions Mgr to get it to work.

**Comment by liydu** [comment]
@klday could you let us know which document you are referring to? So that we can update the doc accordingly. Thanks.

**Comment by jimbobbennett** [comment]
I've raised a PR to correct the MacOS file path: #579

**Comment by jimbobbennett** [comment]
Raised a more specific issue for the Arduino extension not being installed as part of the getting started guide - #580. A PR for the fix for that one is #581.

**Comment by jimbobbennett** [comment]
@liydu - the document is docs/iot-devkit/devkit-get-started.md

**Comment by dilin-MS** [comment]
@jimbobbennett Thanks for your work. Docs has now been updated. #579
