### ISSUE TITLE
The Arduino extension is not mentioned in the getting started guide

### ISSUE THREAD

**Issue by jimbobbennett** [Microsoft/vscode-iot-workbench#580]
The getting started guide (https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-get-started.md) doesn't include a step to install the Arduino extension.

It was added to other docs as part of this commit:

https://github.com/Microsoft/vscode-iot-workbench/commit/e26131e5c07886c656279324e7ac6304162988f1

But not the getting started guide linked to from the VSCode start page.

**Comment by dilin-MS** [comment]
PR merged #581 and thanks for your work :)
