### ISSUE TITLE
[DevKit_State] IoT Hub Connection String Environment variable

### ISSUE THREAD

**Issue by rbrundritt** [Microsoft/vscode-iot-workbench#583]
The sample: https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-state.md doesn't tell you to set the iotHubConnectionString environment variable or how to do it. After a couple of hours of trying to figure out why my Azure function wasn't working I figured this out after reading a different article.

**Comment by Sneezry** [comment]
iotHubConnectionString environment variable should be set automatically. I will verify that on my side.

**Comment by rbrundritt** [comment]
I'd note that I was starting from scratch and this was the first how-to I attempted with IoT Hub, so nothing would have been loaded in from previous articles.

**Comment by Sneezry** [comment]
I tested it, and it works as expected on my side. `iotHubConnectionString` environment variable can be set automatically, and it should be just ignored for users.

I recorded a video to show how it works on my side: https://youtu.be/uuU8Depcqkg

**Comment by rbrundritt** [comment]
OK.
