### ISSUE TITLE
open examples very slow. User experience is not good.

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#586]
![image](https://user-images.githubusercontent.com/35018765/54249999-152cd900-457d-11e9-9d22-0249c0b97c21.png)

Steps:
1.Workbench: Open Examples...
2.select IoT Devkit
3.[Starting] Update package index files... 
4.[Starting] Install package – AZ3166... 
now it take 2 minutes to open page

step3-4 will use lots of times , I can't understand why do steps3-4 when open examples.

step3-4 is unnecessary, Can remove it ?

**Comment by Sneezry** [comment]
Sould be fixed in the latest version.
