### ISSUE TITLE
always install package when create new project

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#587]
pre-steps:
1.prepare a clean machine and not install AZ3166 package

steps:
1.install workbench extension in VSCode
2.workbench:create project---- select IoT Devkit---select Device only---select path
then it will auto-Update package index files and auto-Install package - AZ3166
3. Device project will open in a new windows then close this new windows of Device project
5. create another project with Azure IoT Hub
it will install package AZ3166 again

if it is by design to install package in steps2,  why step5 will install package again?

**Comment by Sneezry** [comment]
fixed.
