### ISSUE TITLE
[Ubuntu18.04]cannot open the serial port : permission denied

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-iot-workbench#588]
repro on vscode 1.32.1
OS: Ubuntu 18.04

step:
1.open Get-Started example
2.Provision Azure Services successfully
3.Configure Device Settings 
cannot open the serial port : permission denied
![image](https://user-images.githubusercontent.com/35018765/54260783-e7f42100-45a4-11e9-9ea2-7701eb3b7a1b.png)

**Comment by Sneezry** [comment]
You need to add current user to the group which has permission to access serial port. See https://askubuntu.com/questions/58119/changing-permissions-on-serial-port

**Comment by czgtest** [comment]
fix work , Thanks a lot!
