### ISSUE TITLE
command 'iotworkbench.examples' not found

### ISSUE THREAD

**Issue by DanKline** [Microsoft/vscode-iot-workbench#589]
I have tried several times installing the Azure IOT-Devkit.  I have Arduino 1.8.8 on Win10 and the MX IOT-DevKit.  The iot workbench open examples and other commands appear to be missing.

Name: Azure IoT Device Workbench
Id: vsciot-vscode.vscode-iot-workbench
Description: Integrated environment to enable easy development on IoT prototype devices (e.g. MXChip IoT DevKit, teXXmo IoT Button, ESP32 and Raspberry Pi) with multiple Azure services.
Version: 0.2.4
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-iot-workbench

**Comment by Sneezry** [comment]
Hi @DanKline , can you provide more details? What version of VS Code are you using? Does iot workbench open examples command never work? Can you execute any other iot workbench command? Can you see any error in developer tool console? You can open developer tool from help - toggle developer tools menu in VS Code.

**Comment by DanKline** [comment]
![image](https://user-images.githubusercontent.com/3081226/54362709-ceec7e00-463f-11e9-9946-da38b2c0ff24.png)
 Open Examples never works
![image](https://user-images.githubusercontent.com/3081226/54362828-09561b00-4640-11e9-9979-3bd63bb4fcc2.png)
![image](https://user-images.githubusercontent.com/3081226/54363047-7d90be80-4640-11e9-85a5-f9cb9170d41c.png)

**Comment by Sneezry** [comment]
It seems Azure account extension has been diabled or uninstalled, you need enable or install it. You can get it from https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account
