### ISSUE TITLE
Raspbian or Windows IoT Core

### ISSUE THREAD

**Issue by baqwas** [Microsoft/vscode-iot-workbench#608]
The documentation is not clear up front on the image for the **Raspberry Pi** board - Raspbian or Windows IoT Core. The **SSH** configuration (instead of **PowerShell**) is the only visible clue. Perhaps, it would be good to have an explicit declaration up front.

Just a suggestion; certainly not an issue!

Regards.

**Comment by dilin-MS** [comment]
Hi, thanks for your kind reminding.
Are you saying the [Raspberry Pi get started docs](https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/raspberry-pi/raspi-get-started.md) is not very clear? We use **ssh** to connect your host machine with the Raspberry Pi hardware. You can use ssh in powershell or WSL or linux terminal.
Can that resolve your confusion? Please feel free to tell us if you still have question!

**Comment by baqwas** [comment]
In my mind using Raspberry Pi within Windows _eco-system_ creates a Pavlovian response for Windows IoT Core examples. The article does not _explicitly_ state right up front that a Raspberry Pi with Raspbian is needed for the exercise. It is my fault for jumping the gun to the wrong conclusion.

After completing the exercise successfully with a Raspbian image, I realized that _I had been too hasty with my initial comment_. This is a dilemma for most of _us who would like to see greater use of Windows IoT Core_ (**NOT** Enterprise) but find that Raspbian is the easy way out for most practitioners (I have two RPi boards _lying in reserve waiting_ for better Windows IoT Core exercises! :). _Just one sentence_ in the leading section of the article would have prevented me being so hasty with my comment.
