### ISSUE TITLE
Group enrollment of MXChip IoT DevKit to DPS using X509 Certificate

### ISSUE THREAD

**Issue by tsghosh** [microsoft/vscode-iot-workbench#610]
I am trying to onboard few MX Chips (AZ3166) on to Azure DPS using group enrollment (X-509).

I have generated a root certificate and a device certificate. (as per example: https://github.com/Azure/azure-iot-sdk-node/tree/master/provisioning/tools)
The root certificate is uploaded to DPS service. The configuration is tested successfully (using a node.js program)  with iothub though dps service.

Now, I like to know how to store the X509 device certificate to IoTdevkit (MX Chip), to simulate a real-world scenario ?

**Comment by ArthurMa1978** [comment]
Sorry, devkit not support group enrollment now

**Comment by johnadali** [comment]
> Sorry, devkit not support group enrollment now

Is this now supported? Looking for an update to this
