### ISSUE TITLE
[ubuntu]Serial monitor has not been started when Configure Device Settings

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-iot-workbench#614]
repro on ubuntu 18.04
step:
1.open example of get started
2.Azure IoT Device Workbench: Provision Azure Services
3.Azure IoT Device Workbench: Configure Device Settings
verify there is a warning "Serial monitor has not been started", it always pop up on ubuntu
![image](https://user-images.githubusercontent.com/35018765/57191183-32ff3480-6f55-11e9-9c2f-dbaf416dd814.png)
verify configure device settings successfully.
4.serial monitor also work well.

if the serial monitor can't work,  I can understand this warning, but now the serial monitor work well , why this warning will pop up?

**Comment by zunhu** [comment]
same issues on windows and macOS.

**Comment by ArthurMa1978** [comment]
It's an Arduino issue, fixed and will be released soon.
