### ISSUE TITLE
Source Code for Get Started with MXChip IoT DevKit Sample

### ISSUE THREAD

**Issue by gregdegruy** [microsoft/vscode-iot-workbench#620]
The initial step for device programming is 

> Find Get Started and click Open Sample button. A new VS Code window with a project folder in it opens.

**Where is the source code for this sample? I'd like to fork it**

![open-sample](https://user-images.githubusercontent.com/8151045/57735469-90803900-7659-11e9-9e43-5eccac67b287.png)

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 0cf9b53c-0438-f23c-fd2e-d57481d57e85
Version Independent ID: f01afd66-d093-ac44-2b20-df225530b39e
Content: IoT DevKit to cloud -- Connect IoT DevKit AZ3166 to Azure IoT Hub
Content Source: articles/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started.md
Service: iot-hub
GitHub Login: @wesmc7777
Microsoft Alias: wesmc

**Comment by liydu** [comment]
Hi @gregdegruy , you can find all source codes for sample here: https://github.com/IoTDevEnvExamples.

And that's a good reminder that we should include that link in the docs.

**Comment by ArthurMa1978** [comment]
@gregdegruy please check https://github.com/IoTDevEnvExamples/DevKitGetStarted
