### ISSUE TITLE
"Configure Unique Device String (UDS) completely." is misleading

### ISSUE THREAD

**Issue by danielvaughan** [microsoft/vscode-iot-workbench#622]
The text:

"Configure Unique Device String (UDS) completely."

I suggest an error;  the string is currently incomplete.

If the intention is to tell the user the operation was successful, I suggest changing to:

"Configure Unique Device String (UDS) completed successfully."

**Comment by ArthurMa1978** [comment]
good catch

**Comment by JerryYangKai** [comment]
Hi, thank you for your suggestion. We will change the text in next feature released.
