### ISSUE TITLE
MXCHIP AZ3166 serial port button not work

### ISSUE THREAD

**Issue by br1pro** [microsoft/vscode-iot-workbench#661]
I'm following this tutorial https://microsoft.github.io/azure-iot-developer-kit/docs/get-started/ to connect my AZ3166 to Iot Hub.
The tutorial explain how to run the "Get started" tutorial.
In the section "Build your first project" I'm blocked at point 5. If I click on the "select serial port" button in the right down corner, nothing happens.
I'm using the last firmware 1.6.2 and visual studio code on a win10 pc.
![image](https://user-images.githubusercontent.com/23063162/60703158-59176580-9f01-11e9-8a8d-48abde4eca92.png)

**Comment by br1pro** [comment]
The serial port works well if I try to open it from Putty, so I think this is a VScode issue

**Comment by rploeg** [comment]
I have the same issue (also latest versions). The only strange thing I have, is one project in the library I see the serial port and I can deploy code. When I create a new IoT workbench project, I cannot select the serial port

**Comment by ArthurMa1978** [comment]
This is happened since vs code 1.36 released last week, we're working on the fix

**Comment by ArthurMa1978** [comment]
Same issue reported in Arduino extension: https://github.com/microsoft/vscode-arduino/issues/851

**Comment by ArthurMa1978** [comment]
Fixed since v0.3.1, thanks @br1pro  and @rploeg

**Comment by balakreshnan** [comment]
I have the same problem now. Cannot open serial port and assign mxchips.

**Comment by J-o-h-n-M** [comment]
Same issue today
