### ISSUE TITLE
IoT DevKit OTA failed: FileSizeNotMatch

### ISSUE THREAD

**Issue by akhtarusafzai** [microsoft/vscode-iot-workbench#680]
Hello, I have setup the azure account with a hub, storage and configurations for the firmware to be updated on the device via OTA. I have followed the same guide step by step. The Device detect a new version but gives an error while downloading it, 

> IoT DevKit OTA failed: FileSizeNotMatch

![image](https://user-images.githubusercontent.com/23333346/61699289-14d6f280-ad54-11e9-9c29-cbbeecb4d69b.png)

**Comment by JerryYangKai** [comment]
Hi, we have released workbench 0.10.15 and fixed the bug. You can create a new sample project and check it.
