### ISSUE TITLE
"Unit" type urn: values fails device code generation

### ISSUE THREAD

**Issue by ericwol-msft** [microsoft/vscode-iot-workbench#690]
With the latest RC release, unit type for device properties schema now populates the vale with the urn for the units. Generating the device code fails with the following error:

`Name=urn:azureiot:v1:classes:Units:Pressure:kiloPascal:1, Id=Unit, Description=Not a supported unit`

Setting the unit type to "Units/Pressure/kiloPascal" allows the device to be generated, but fails validation.

**Comment by ArthurMa1978** [comment]
fixed in 0.10.10
