### ISSUE TITLE
How to use cross compiler (container) to build from cmake (with -D) instead of from a VSCode project.

### ISSUE THREAD

**Issue by yphuangms** [microsoft/vscode-iot-workbench#707]
Is it possible to use VS Code with cross compiler container to build the whole Azure IoT device C SDK?

**Comment by dilin-MS** [comment]
Hi, 
Follow the [tutorial](https://github.com/microsoft/vscode-iot-workbench#embedded-linux-public-preview) to create an IoT workbench embedded linux project. You can choose `32-bit Armv7 Cortex-A` or `64-bit Armv8 Cortex-A` cross-compile container. The container contains the [azure-iot-device-sdk](https://github.com/Azure/azure-iot-sdk-c). Edit your application and trigger compile command to cross-compile your application with the Azure IoT device C SDK.
The compilation use cmake to build sdk.
Feel free to tell me if you still have question on it.

**Comment by yphuangms** [comment]
There's no way to modify cmake command line options, for example, what if I want to enable provisioning client? The script to trigger the build is a file inside container, and it's not documented. 
There should be steps in document to show how to customize the build script and keep this user-defined build script within VSCode project.

Thanks!

**Comment by dilin-MS** [comment]
Currently we does not support customization of the cmake command option. We will take that into account.
As a workaround, if you need to customize the build script, you can run cmake command directly in VS Code bash terminal which is open in container. Run the cmake build command under directory `/work/azure-iot-sdk-c/cmake`. Check the [bash script](https://github.com/microsoft/vscode-iot-workbench/blob/master/devicedevex_dockerfiles/public/iot-device-cube-1.0.0/azure-c-app-20190411-ubuntu-arm64/compile_app.sh) to see what the `Azure IoT Device Workbench: Compile Device Code` command do if you encounter problems.

**Comment by yphuangms** [comment]
This is mostly documentation issue, it's difficult for developer to understand how it works without explicitly point it out in document, and make this tool even useful to facilitate their work.

This is possible even in current design. For example, I copy the bash script "compile_app.sh" to the project root folder, hence it will appear on container at "/workspaces/[project_name]/compile_app.sh".

And then, modify "buildCommand" in [current project]/.vscode/config.js to run the script:

`"buildCommand": "bash ./compile_app.sh ./src",`

By doing so, developer can manage the build script within the VSCode project. It would be good if this approach is provided by create a new project.

**Comment by dilin-MS** [comment]
This is not our recommended practice, so we didn't add it in documentation.
We plan to expose customized build command entry. It will be implemented later.

**Comment by dilin-MS** [comment]
Hi, @yphuangms we have enabled Vcpkg in containerized toolchain. The development experience will be more smooth and this issue is resolved in the latest v0.10.17 Azure IoT Device Workbench. 
In the new flow, you can edit build command in `build.sh` file or edit the compile task in `./vscode/tasks.json`. We expose more extensibility to user.
