### ISSUE TITLE
[Upload Device Code] When modify target binary name, it fails to upload device code to target device. Error shows "Binary file does not exist"

### ISSUE THREAD

**Issue by yphuangms** [microsoft/vscode-iot-workbench#716]
By following the document to create a project, which containing the basic IoT Hub sample, and then all is fine to run "Azure IoT Device Workbench: Compile Device Code" to build the code, and then to run "Azure IoT Device Workbench: Upload Device Code" to the target device.

But this project is not supposed to be restricted to this use as an IoT Hub sample. When I modify the source code and CMakeLIsts.txt to rename the target executable binary name, it's Ok to build, but results in error when attempting to upload the output binary to device.

The message in OUTPUT window shows:

> "Unable to upload the sketch, please check output window for detail.Unable to upload the sketch, please check output window for detail."

There are errors and warnings in notification:
![image](https://user-images.githubusercontent.com/14900924/63000735-73e7dd00-bea4-11e9-8e8f-47893a318d4a.png)

It seems like VS Code remember the executable binary name at first "Upload Device Code", and then it keeps using this name, and there's no way for developer to modify this name.

It's not a good idea to modify the source code while keep the executable binary name always called "azure_iot_app". Please make it configurable by developer.

Thanks!

**Comment by yphuangms** [comment]
After some trial and error, the binary name "azure_iot_app" and the folder name "iot_applicaiton" cannot be modified, or the tool will complain the Binary file does not exist.
Even if I modify the name before first compile of code, the result is still the same, only "iot_applicaiton/azure_iot_app" is acceptable by this tool.

**Comment by dilin-MS** [comment]
Thanks for trying out the containerized device toolchain feature and the valuable feedback. Solution to improve this experience is under development and will come out soon.

**Comment by dilin-MS** [comment]
Hi, @yphuangms we have enabled Vcpkg in containerized toolchain. The development experience will be more smooth and this issue is resolved in the latest v0.10.17 Azure IoT Device Workbench. Please take a try~
