### ISSUE TITLE
Distinguish the ESP32 sample from official and community

### ISSUE THREAD

**Issue by liydu** [microsoft/vscode-iot-workbench#720]
It will have different support level so better we distinguish it just like the DevKit sample gallery.

**Comment by liydu** [comment]
Take DevKit sample gallery as an example:

<img width="1164" alt="Screen Shot 2019-08-20 at 11 36 04 AM" src="https://user-images.githubusercontent.com/17307692/63316059-2eae2a00-c340-11e9-9e91-151458f8a711.png">

**Comment by JerryYangKai** [comment]
Done
