### ISSUE TITLE
New MXChip project has no delay in loop

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/vscode-iot-workbench#729]
I created a new MXChip project with an IoT Hub.

In the `loop` function the delay is commented out. This is not great as it can quickly use up the free tier daily limit.

Can this be uncommented please.

**Comment by JerryYangKai** [comment]
Hi @jimbobbennett , we will fix it in next feature released

**Comment by JerryYangKai** [comment]
Hi, @jimbobbennett . Thanks for advising,  we have fixed it in our new workbench. You can check it in version 0.10.16
