### ISSUE TITLE
IoT Hub connection details are stored in the workspace file

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/vscode-iot-workbench#730]
If I create a new project containing an IoT Hub, the connection details including the IoT Hub connection string are embedded in the workspace file.

This is dangerous, as I'd want to check these files into source code control, which is a problem for open source code, or developers using different hubs.

These connection details are also in the `azureconfig.json` file, so could this be added to the .gitignore to avoid checking in credentials?

**Comment by shizn** [comment]
@ArthurMa1978 Could you help take care of this issue?

**Comment by JerryYangKai** [comment]
Hi @jimbobbennett , thanks for your suggestion. We will generate a .gitignore containing these files when user create a new project. This will be fixed in next feature released.

**Comment by jimbobbennett** [comment]
@JerryYangKai - yes for the azureconfig.json. But for the workspace file it needs to be checked in, so not in the .gitignore. For this can you remove the connection details from the workspace files.

**Comment by chagong** [comment]
@jimbobbennett This issue has been fixed by moving credential info to .azureconfig.json file. The workspace file will not contain any sensitive info any more. Please check it out.
