### ISSUE TITLE
Raspberry Pi is missing from Azure IoT Device Workbench Examples 

### ISSUE THREAD

**Issue by sphinxy** [microsoft/vscode-iot-workbench#734]
Manual for raspberry pi says "Open Azure IoT Device Workbench Examples" and select Raspberry PI here. 

https://github.com/microsoft/vscode-iot-workbench/blob/b335b2d8f94a7ea63cc019e189015478d5cd5a01/docs/raspberry-pi/raspi-get-started.md#L60-l68

On two different PC I have only "MXChip IoT DevKit" and "Generic RSP32 boards".

How it can be fixed or where I can get examples manually?

**Comment by zunhu** [comment]
Hi, You can find code and docs in below links for workaround.
Code: https://github.com/IoTDevEnvExamples 
Docs: https://github.com/microsoft/vscode-iot-workbench/tree/master/docs/raspberry-pi

**Comment by vslepakov** [comment]
Couldn't select RasPi in the samples dialog either.
But with this (see screenshot) you can start developing for RasPi in a devcontainer:

![image](https://user-images.githubusercontent.com/1545509/63915394-47040000-ca36-11e9-81ab-2587c5e0985b.png)

**Comment by zunhu** [comment]
Yes, it is. Devcontainer is support for RasPi.

**Comment by zunhu** [comment]
Remove RaspberryPi  example is by design, users can use devcontainer for RaspberryPi develop.
