### ISSUE TITLE
submit files to model repository has no effect

### ISSUE THREAD

**Issue by vslepakov** [microsoft/vscode-iot-workbench#736]
Hi,

the above functionality does not seem to work in VSCode. 
It asks for a file but does nothing then and there is no output.

Thanks

**Comment by zunhu** [comment]
hi, do you have any screenshot?
this is submit file example and you need to open folder which contain these files.
•	[EnvironmentalSensor.interface.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FIoTToolingTeam%2FEV1_S1iNK6tHmQGCmoe5ipQBQkfOT-VlOLSJlh2LvDuUbw%3Fe%3DlDy9Nw&data=02%7C01%7Cerichen%40microsoft.com%7Cbdb2026570a24842ca9f08d70b2f93d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636990171301350106&sdata=IUl6ase62rzVdm2sb1rn6gn%2BZvlmVDBMhfcI%2FpNaNmA%3D&reserved=0)
•	[SampleDevice.capabilitymodel.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FIoTToolingTeam%2FEQDfZsKKOO9OrZskHLi4n-gBxtqUg9cfrUBbpLFqoI0x7w%3Fe%3D6UMREf&data=02%7C01%7Cerichen%40microsoft.com%7Cbdb2026570a24842ca9f08d70b2f93d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636990171301350106&sdata=ndDCaAVP74LTSplvHuiKcVA1niVPqr3PP1J41ZMj2bs%3D&reserved=0)

**Comment by vslepakov** [comment]
Ok, got it to work.

So the problem was: if you just select a file using arrow keys (in the dialog in the screenshot) and then hit enter this file is not selected which is why nothing happens.

![image](https://user-images.githubusercontent.com/1545509/63913974-23d75180-ca32-11e9-961f-1e386348da50.png)
