### ISSUE TITLE
[Embedded Linux Project] What is the recommended approach to adding external libs such as WiringPI?

### ISSUE THREAD

**Issue by darenm** [microsoft/vscode-iot-workbench#744]
What is the recommended approach to adding additional SDKs, libraries, etc. to the development environment? I am building apps that leverage GPIO to work with external sensors, etc. and typically use [wiringPI](http://wiringpi.com/).

**Comment by dilin-MS** [comment]
Hi, we are currently working on this extensibility feature.
For now you can add the needed script in `./.devcontainer/Dockerfile` and rebuild the container using vscode "remote-development" extension's command `Remote-Containers: Rebuild Container` to rebuild the docker image. In this way, you can add the needed external libs in your image.

**Comment by darenm** [comment]
OK - thank you.
