### ISSUE TITLE
Stub Code - Readme Issue

### ISSUE THREAD

**Issue by khilscher** [microsoft/vscode-iot-workbench#778]
When generating the C stub code for Plug and Play, it generates a Readme. In the Readme, it references a azure-iot-sdk-c-pnp folder. This is incorrect. The folder is azure-iot-sdk-c.

**Comment by dooriya** [comment]
@khilscher Thank you for your feedback.
We have fixed this wording issue in the README.md and will release a new Workbench extension at the end of Next Week.

**Comment by xinyiz1226** [comment]
@khilscher the fix is included in Device Workbench 0.10.16, please try and see if it fixes your problem
