### ISSUE TITLE
Creating a new project gives broken c_cpp_properties file

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/vscode-iot-workbench#780]
# To reproduce

Create a new IoT project (I tried using MXChip and ESP32)

# Expected:

`c_cpp_properties.json` should contain relevant properties including the include paths

# Actual

`c_cpp_properties.json` has a single entry saying `[object Promise]`

**Comment by zunhu** [comment]
Hi, I used VSCode 1.39.2 and IoT workbench 0.10.15 on windows10, can't repro this issue.

Would you please let me know test environments?

**Comment by jimbobbennett** [comment]
VS Code 1.39.2, IoT Workbench 0.10.15, macOS Mojave 10.14.6. So could be a Mac issue?

**Comment by zunhu** [comment]
it will be fixed in next release(next week), I will do confirm and let you know in next week.

**Comment by hellyzh** [comment]
@jimbobbennett , we have released IoT Workbench 0.10.16, please try it. The issue has been fixed in this latest version.

**Comment by jimbobbennett** [comment]
Looks good to me! Tested and creates the correct `c_cpp_properties.json` file.
