### ISSUE TITLE
VS Code disconnects from WSL after 1.39 update 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-iot-workbench#789]
here is  [one customer  ](https://github.com/ahernandez-allegion)  report an issue to workbench.

Issue Type: Bug
I had initially filed an issue for Remote-WSL but they asked me to report it over here:
microsoft/vscode-remote-release#1646
After the automatic update to 1.39, the WSL extension is disconnecting from WSL. This happens after I manually connect, run code . from WSL, or use "Open Recent". It seems to connect briefly for about 5 seconds then disconnects and gives me this pop-up:
"Cannot reconnect. Please reload the window".
It gives me two options: Reload window or Cancel. If I Reload window, it just happens again.

![image](https://user-images.githubusercontent.com/35018765/67541671-66f52e80-f71c-11e9-9598-7c59118b2cef.png)

I've been working in VS Code with WSL perfectly fine today until after the update.
After further research, the extension Azure IoT Device Workbench was causing the problem. Disabling the extension allows me to continue using Remote-WSL. The WSL log does not show anything notable. There does not appear to be any settings for this extension but I have the following information:

`Name: Azure IoT Device Workbench
Id: vsciot-vscode.vscode-iot-workbench
Description: Integrated environment to enable easy development on IoT prototype devices (e.g. MXChip IoT DevKit, teXXmo IoT Button, ESP32 and Raspberry Pi) with multiple Azure services.
Version: 0.10.15
Publisher: Microsoft
VS Marketplace Link: `https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-iot-workbench`

`Extension version: 0.39.9
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
System `Info`

**Comment by czgtest** [comment]
please refer to  https://github.com/microsoft/vscode-azure-iot-toolkit/issues/421

**Comment by zunhu** [comment]
thanks for your reporting, it is fixed and will release new version in next week.

**Comment by dilin-MS** [comment]
Hi, @czgtest this issue is fixed in the latest Azure IoT Device Workbench v0.10.16. Please take a look. :)

**Comment by czgtest** [comment]
wait for user's response.

**Comment by ahernandez-allegion** [comment]
This is resolved now, thank you!
