### ISSUE TITLE
Interfaces not shown in the public model repository

### ISSUE THREAD

**Issue by rido-min** [microsoft/vscode-iot-workbench#809]
Using version 0.10.16 `Open Model Repository`

![image](https://user-images.githubusercontent.com/14916339/68259142-e1139600-ffed-11e9-804a-979248a461e9.png)

**Comment by eriolchan** [comment]
@rido-min I think it is service side problem of model repository. Both interface and capability model can be shown since this Monday for me, can you help try it again?

**Comment by eriolchan** [comment]
@rido-min we have fixed this bug and will release it in the next version, nice catch.

**Comment by eriolchan** [comment]
@rido-min this issue has been resolved in the latest Azure IoT Device Workbench v0.10.17. Please try it again. Thank you for your active participation.
