### ISSUE TITLE
Cannot configure device connection string

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/vscode-iot-workbench#829]
Using an MXChip board, I have created an IoT Hub MXChip application with a single device.

When I configure the device settings to set the connection string, instead of getting the prompt to put the device in configuration mode, followed by the popup saying the device is configured, nothing happens - no prompt, no popup and the device settings are not pushed to the MXCHip board.

I'm using the MXChip firmware 1.6.34, VS Code 1.40.1, IoT Hub toolkit 2.13.0

**Comment by eriolchan** [comment]
@jimbobbennett this issue is caused by VS Code 1.40.1 upgrade, we have fixed it in the next release of 0.10.17.

**Comment by dilin-MS** [comment]
Hi, this issue has been resolved in the latest Azure IoT Device Workbench v0.10.17. You can try it out in the new release.Thanks for your active participation.

**Comment by jimbobbennett** [comment]
Tested with the latest IoT workbench and it's all working.

Thanks!
