### ISSUE TITLE
devkit-get-started.md needs update

### ISSUE THREAD

**Issue by chagong** [microsoft/vscode-iot-workbench#904]
In the section  "Test the project" of "docs/iot-devkit/devkit-get-started.md", probably due to the change in vscode there is no context menu item called "Start monitoring D2C message". 

[https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-get-started.md](url)

**Comment by liydu** [comment]
Fixed with: https://github.com/Azure-Samples/mxchip-iot-devkit-get-started/pull/3
