### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by lokijota** [microsoft/vscode-iot-workbench#917]
In the main readme (`https://github.com/microsoft/vscode-iot-workbench/blob/master/README.md`) the link to "Use Azure IoT Device Workbench extension in Visual Studio Code" is broken. It points to which doesn't exist (error 404).

**Comment by xinyiz1226** [comment]
Thank you for reporting. We will find the right document and update the link soon.

**Comment by dilin-MS** [comment]
The link has already been updated. Thanks for your active participation! :)
