### ISSUE TITLE
couldn't find the code for m5stack-email-receiver run.csx file

### ISSUE THREAD

**Issue by apoorvanand** [microsoft/vscode-iot-workbench#954]
Hi,
Unable to find run.csx file in the repo for m5stack-email-receiver code as mentioned in file https://github.com/microsoft/vscode-iot-workbench/blob/master/docs/esp32/m5stack-email-receiver.md

**Comment by JerryYangKai** [comment]
Hi @apoorvanand, this sample is out of date and we will no longer support it. So we changed it to archived two month ago.

**Comment by apoorvanand** [comment]
@JerryYangKai  Can you please provide the link of the archieved one so that I can try out once with my esp32

**Comment by JerryYangKai** [comment]
@apoorvanand  Link is here.
https://github.com/IoTDevEnvExamples/M5StackEmailReceiver

**Comment by apoorvanand** [comment]
Thanks for providing the link @JerryYangKai

**Comment by apoorvanand** [comment]
@JerryYangKai  How to deploy the funtion app , which option to select durng deployment

**Comment by apoorvanand** [comment]
@JerryYangKai  Unable to search the azure functions even if they are in same region .Is this bug with Azure
