### ISSUE TITLE
jsonValidation contribution breaks other JSON users

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-iot-workbench#958]
From https://github.com/microsoft/vscode/issues/94282

- install the Azure IoT Device Workbench extension
- open a JSON file with content `[ 1, 2, 3 ]`
- error markers on the file

This is caused by following the jsonValidation contribution. The fileMatch is far to general.

```
		"jsonValidation": [
			{
				"fileMatch": "*.json",
				"url": "./resources/pnp/templates/emptySchema.json"
			}
		],
```

**Comment by dominikdalek** [comment]
There's nothing to update. The `fileMatch` is way too agressive.

**Comment by eriolchan** [comment]
@aeschli  @dominikdalek thanks for your good feedback, we will fix this in the next release.

**Comment by eriolchan** [comment]
The fix has been merged to develop branch, will be released in the next version.
