### ISSUE TITLE
[PnP]diagnostic message persists after deleting or renaming  interface file

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-iot-workbench#964]
Steps to reproduce
1.Open Command Palette and select “IoT Plug and Play: Create Interface”. 
2.Input name such as “myInterface”. 
3.verify there is a myinterface.interface.json file in the target folder and open it. 
4.Notice there is an error shown in VS Code's problem panel now.
![image](https://user-images.githubusercontent.com/35018765/80562769-4a171c00-8a1b-11ea-97fd-ddc341adcf3f.png)
4.delete or rename myinterface.interface.json
5.verify the diagnostic message persists in problem panel and you cannot make remove it unless you reload or restart VS Code.

**Comment by eriolchan** [comment]
This is the behavior of VSCode, it will refresh the Problems panel after a while.
