### ISSUE TITLE
C/C++ IntelliSense show problem for "strdup" function in the "Get Started" example of Mxchip IoT DevKit

### ISSUE THREAD

**Issue by hellyzh** [microsoft/vscode-iot-workbench#984]
C/C++ IntelliSense show problem `identifier "strdup" is undefined` for "strdup" function in the "Get Started" example of Mxchip IoT DevKit.
![image](https://user-images.githubusercontent.com/49181894/90480666-25c68300-e163-11ea-8f3d-8b99f5191a9e.png)

**Comment by dilin-MS** [comment]
The issue is fixed in the latest v0.16.0.
